<?php
$z[0]=Array("pubdate","",67,110);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",142,185);
$z[1][4]['function']="MyDate('M',@me)";
$z[2]=Array("pubdate","",193,236);
$z[2][4]['function']="MyDate('y',@me)";
$z[3]=Array("litpic","",285,300);
$z[4]=Array("arcurl","",368,383);
$z[5]=Array("title","",385,399);
$z[6]=Array("typename","",453,470);
$z[7]=Array("description","",753,803);
$z[7][4]['function']="cn_substr(@me,158)";

?>