<div class="list">
	<div class="lists">
	<a href="[field:arcurl/]" class="imgs"><img src="[field:litpic/]" onerror="this.src='/include/noPic.jpg'" border="0"/></a>
	<div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
	<div class="coms">[field:info/]...</div>
	<span class="a1"></span>
	<span class="a2"></span>
	<span class="a3"></span>
	<span class="a4"></span>
	<span class="a5"></span>	</div>
</div>