<?php
$z[0]=Array("global","",189,221);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",307,339);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n              ",469,674);
$z[2][4]['type']="top";
$z[2][4]['row']="6";
$z[2][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[3]=Array("global","",865,897);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",960,992);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1082,1114);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1177,1209);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1286,1318);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1381,1413);
$z[8][4]['name']="cfg_templets_skin";

?>